---
- name: Update Nginx Configuration
  hosts: localhost
  become: true
  tasks:
    - name: Backup existing nginx.conf file, if it exists
      command:
        cmd: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org
      args:
        creates: /etc/nginx/nginx.conf.org
      ignore_errors: true

    - name: Create new nginx.conf file
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;
          include /usr/share/nginx/modules/*.conf;
          events {
              worker_connections 1024;
          }
          http {
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';
              access_log  /var/log/nginx/access.log  main;
              sendfile            on;
              tcp_nopush          on;
              tcp_nodelay         on;
              keepalive_timeout   65;
              types_hash_max_size 4096;
              include             /etc/nginx/mime.types;
              default_type        application/octet-stream;
              include /etc/nginx/conf.d/*.conf;
          }
        mode: '0644'
    - name: Resart mariadb rabbitmq-server memcached nginx
      command:
        cmd: systemctl restart mariadb rabbitmq-server memcached nginx
    - name: Resart mariadb rabbitmq-server memcached nginx
      command:
        cmd: systemctl enable mariadb rabbitmq-server memcached nginx
    - name: rabbitmqctl add_user openstack password
      command:
        cmd: rabbitmqctl add_user openstack password
    - name:  rabbitmqctl set_permissions openstack ".*" ".*" ".*"
      command:
        cmd: rabbitmqctl set_permissions openstack ".*" ".*" ".*"


